server:
  port: 8003
spring:
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      server-addr: localhost:8848
  application:
    name: service-note
  datasource:
    url: jdbc:mysql://localhost:3306/article?serverTimezone=UTC
    username: root
    password: 20050702cj
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'chen'
      paths-to-match: '/**'
      #生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: org.ash
# 阿里云 OSS 配置
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t9VTbZhqBZfJaSwzCkg
    access-key-secret: SnPy6YT8LTshCKS3MH2i4Yhwz9ICGN
    bucket-name: note-flow # 默认存储桶
#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: true
    username: chen
    password: 123456
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 用户模块
#spring.jpa.show-sql=true
#???sql
#spring.jpa.properties.hibernate.format_sql=true;
#???????????????
